### ISSUE TITLE
User is "jboss-eap-6.4" instead of "jboss"

### ISSUE THREAD

**Issue by jaaviercr** [daggerok/jboss-eap-6.4#1]
When I enter in the container I see the user is actually "jboss-eap-6.4" and not "jboss". The problem with this name is that "chown" linux command does not work properly.

From [info coreutils 'chown invocation' for GNU coreutils:](http://www.gnu.org/software/coreutils/manual/html_node/chown-invocation.html)

> Some older scripts may still use ‘.’ in place of the ‘:’ separator. POSIX 1003.1-2001 (see Standards conformance) does not require support for that, but for backward compatibility GNU chown supports ‘.’ so long as no ambiguity results. New scripts should avoid the use of ‘.’ because it is not portable, and because it has undesirable results if the entire owner‘.’group happens to identify a user whose name contains ‘.’.

Is there any way to change the user?

**Comment by daggerok** [comment]
Hey,
Which image version you are using? show me at least part of your Dockerfile

**Comment by jaaviercr** [comment]
Dockerfile:
```
FROM daggerok/jboss:eap-6.4
MAINTAINER jaaviercr

WORKDIR ${JBOSS_HOME}

ENV STANDALONE_FOLDER ${JBOSS_HOME}/standalone
ENV CONFIGURATION_FOLDER ${STANDALONE_FOLDER}/configuration
ENV DEPLOYMENT_FOLDER ${STANDALONE_FOLDER}/deployments
```
docker-compose:
```
version: '3'
services:
  jbtest:
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
```
Then build the container and connect through a bash terminal. I am getting the user:
```
test>docker container exec -it javidock_jbtest_1 bash
bash-4.4$ whoami
jboss-eap-6.4
```

**Comment by daggerok** [comment]
Hello @jaaviercr

so you are using another image FROM instruction:

```Dockerfile
FROM daggerok/jboss:eap-6.4
```

that image was built in scope of other my [daggerok/jboss](https://github.com/daggerok/jboss) GitHub repository. User you pointing (`jboss-eap-6.4`), comes [from here](https://github.com/daggerok/jboss/blob/eap-6.4/Dockerfile#L12)

For current repository, you should use different docker image in your Dockerfile, for example:

```Dockerfile
FROM daggerok/jboss-eap-6.4:6.4.21-alpine
```

Please, read carefully current repository [README.md file](https://github.com/daggerok/jboss-eap-6.4/blob/master/README.md#usage) as a reference.

---
Regards,
Maksim

**Comment by jaaviercr** [comment]
Oh, sorry!
Thank you very much for your help! :)

**Comment by jaaviercr** [comment]
I have tried with the proper approach you told me, this is the Dockerfile (I assume that EXPOSE 8080 is not needed):
```
FROM daggerok/jboss-eap-6.4:6.4.21-centos
# debug:
ENV JAVA_OPTS="$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
EXPOSE 5005
# health check:                         
HEALTHCHECK --timeout=1s \
            --retries=33 \
            CMD test `netstat -ltnp | grep 9990 | wc -l` -ge 1 || exit 1
# or:
HEALTHCHECK --timeout=1s \
            --retries=33 \
            CMD wget -q --spider http://127.0.0.1:8080/my-service/health || exit 1
```
docker-compose.yml is as follow:
```
version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
      - "5005:5005"
```
And from inside the container I see JBOSS is working:
```
[jboss@b9092a02b09a ~]$ curl 127.0.0.1:8080
<!DOCTYPE html>
<html>
<head>
[...]
```
It seems port are redirected correctly:
```
PS C:\Users\javi\dtest> docker-compose ps
The system cannot find the path specified.
   Name                  Command                       State                                                     Ports
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
dtest_web_1   /bin/sh -c standalone.sh / ...   Up (health: starting)   0.0.0.0:5005->5005/tcp, 0.0.0.0:8080->8080/tcp, 8443/tcp, 0.0.0.0:9990->9990/tcp, 9999/tcp
```
But I do not why when I try to enter from the browser it does not work.

**Comment by daggerok** [comment]
On . a first glance, seems like your JBoss configuration is allowing to expose only localhost
you can try override your `ENTRYPOINT` instruction right in Dockerfile and pass to `standalone.sh` script `-b 0.0.0.0` argument to tell JBoss: hey, please expose your 8080 port on any interfaces you have (not only loopback: 127.0.0.1):

```Dockerfile
FROM daggerok/jboss-eap-6.4:6.4.21-centos
# ...
ENTRYPOINT standalone.sh -b 0.0.0.0
```

another possibe way for fix is add `-Djboss.bind.address=0.0.0.0` java system property to your `JAVA_OPTS` env variable, like so:

```Dockerfile
FROM daggerok/jboss-eap-6.4:6.4.21-centos
# ...
ENV JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address=0.0.0.0"
```

google: `JBoss listening on all interfaces`
or google these keywords: `JBoss bind 0.0.0.0 address`

if it wont help: please, reopen current issue and provide some github repo, so I could clone and reproduce

---
Regards,

**Comment by jaaviercr** [comment]
Now it works! My approach was wrong, I thought it was related with the container and not JBOSS.
Thank you very much! :D

**Comment by daggerok** [comment]
you are welcome
